### ISSUE TITLE
Incompatibility with Sidekiq 6.0.1 and onwards

### ISSUE THREAD

**Issue by attilagyorffy** [emartech/ezlog#1]
Sidekiq 6.0.1 introduced a method name change and a way to support job specific loggers. This results in a call to `Sidekiq::JobLogger#prepare` (see [here](https://github.com/mperham/sidekiq/commit/fd634c05fdd7cae7252a2929c5427ce22b5e0e5b)) which works just fine within Sidekiq's own `JobLogger` but won't work with `Ezlog::Sidekiq::JobLogger` and fails with a `NoMethodError` during the dispatching of a job.

At this point I'm not entirely sure whether we should support Sidekiq's new functionality or just work around the issue for now. TBD.

**Comment by zormandi** [comment]
Fixed in v0.5.3

**Comment by attilagyorffy** [comment]
@zormandi shall we close this issue then?
