### ISSUE TITLE
Sidekiq 6.5 compatibility

### ISSUE THREAD

**Issue by mhenrixon** [emartech/ezlog#7]
https://github.com/emartech/ezlog/blob/6fc35ff2c0e5496aa5e51e2162920adc6f997d4e/lib/ezlog/railtie.rb#L76

There is no longer a constant named `Sidekiq::ExceptionHandler::Logging`; in fact, there is no constant called `Sidekiq::ExceptionHandling` anymore.

**Comment by foldadamSAP** [comment]
Merged in #8
